spring:
  application:
    name: Distributed-Transaction-Service
  datasource:
    url: jdbc:h2:file:./data/distributedtxdb;MODE=PostgreSQL;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

server:
  port: 8114

management:
  endpoints:
    web:
      exposure:
        include: health,info

# Logging Configuration
logging:
  level:
    com.netflix.eureka: INFO
    com.netflix.discovery: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

